"""Interface contract package.

Concrete IC-1 through IC-6 implementations are added by the owning agents
after the relevant gate freezes the schema.
"""

from src.contracts.loading_trajectory import (
    LoadingTrajectoryResult,
    TimeDomain,
    validate_loading_trajectory_result,
)
from src.contracts.net_load import (
    ALLOWED_COMPONENT_ARTIFACT_STATUSES,
    AcceptedComponentAdapterArtifact,
    ExecutableInputArtifact,
    FutureLayerScreenPreflightConfig,
    GatedAdapterBackedNetLoadProvider,
    ComponentAdapterRegistry,
    ComponentAdapterSkeleton,
    ComponentKind,
    ComponentProvenance,
    REAL_COMPONENT_WIRING_KINDS,
    NetLoadAssemblyPlan,
    NetLoadComponent,
    NetLoadLoadingInputReadiness,
    NetLoadProvider,
    NetLoadResult,
    REQUIRED_INTEGRATION_COMPONENT_KINDS,
    assemble_net_load_from_real_component_outputs,
    assemble_net_load_from_registry_outputs,
    assemble_net_load_from_components,
    build_accepted_artifact_loader_blocker_preflight,
    build_ic1_assembly_plan_from_registry,
    build_component_adapter_registry_from_artifacts,
    build_net_load_result,
    load_component_adapter_output_from_npz_artifact,
    load_net_load_component_from_npz_artifact,
    prepare_loading_input_from_registry_outputs,
    validate_future_layer_screen_preflight,
    validate_executable_input_gate,
    validate_component_adapter_skeletons,
    validate_real_component_adapter_readiness,
    validate_registry_adapter_output_readiness,
    validate_net_load_result,
)

__all__ = [
    "ALLOWED_COMPONENT_ARTIFACT_STATUSES",
    "AcceptedComponentAdapterArtifact",
    "ExecutableInputArtifact",
    "FutureLayerScreenPreflightConfig",
    "GatedAdapterBackedNetLoadProvider",
    "ComponentAdapterRegistry",
    "ComponentAdapterSkeleton",
    "ComponentKind",
    "ComponentProvenance",
    "LoadingTrajectoryResult",
    "NetLoadAssemblyPlan",
    "NetLoadComponent",
    "NetLoadLoadingInputReadiness",
    "NetLoadProvider",
    "NetLoadResult",
    "REAL_COMPONENT_WIRING_KINDS",
    "REQUIRED_INTEGRATION_COMPONENT_KINDS",
    "TimeDomain",
    "assemble_net_load_from_real_component_outputs",
    "assemble_net_load_from_registry_outputs",
    "assemble_net_load_from_components",
    "build_accepted_artifact_loader_blocker_preflight",
    "build_ic1_assembly_plan_from_registry",
    "build_component_adapter_registry_from_artifacts",
    "build_net_load_result",
    "load_component_adapter_output_from_npz_artifact",
    "load_net_load_component_from_npz_artifact",
    "prepare_loading_input_from_registry_outputs",
    "validate_future_layer_screen_preflight",
    "validate_executable_input_gate",
    "validate_loading_trajectory_result",
    "validate_component_adapter_skeletons",
    "validate_net_load_result",
    "validate_real_component_adapter_readiness",
    "validate_registry_adapter_output_readiness",
]
